---
- become: yes
  hosts: all
  connection: ssh
  gather_facts: no

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      notify:
    
    - name: Install vim and apache2 packages
      apt:
        name: '{{ item }}'
        state: present
      loop:
        - apache2
        - vim

    - name: Modify apache2 port
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80'
        line: 'Listen 8080'
      notify:
        - restart apache2

